name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      - name: Installing dependencies
        run: npm install
        
      - name: Building
        run: npm run build
        
  deploy:
    needs: build
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
